// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGabinos.Infrastructure.DataBase.Context;

#nullable disable

namespace SistemaGabinos.Infrastructure.Migrations
{
    [DbContext(typeof(SistemaGabinosDBContext))]
    [Migration("20260807014545_RemoveLegacyCursoData")]
    partial class RemoveLegacyCursoData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SistemaGabinos.Domain.Entities.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CURP")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreTutor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentescoTutor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProximaFechaCobro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoTutor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TieneBeca")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CURP")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("SistemaGabinos.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioLibro")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nivel = "Book1",
                            PrecioLibro = 350m
                        },
                        new
                        {
                            Id = 2,
                            Nivel = "Book2",
                            PrecioLibro = 350m
                        },
                        new
                        {
                            Id = 3,
                            Nivel = "Book3",
                            PrecioLibro = 350m
                        },
                        new
                        {
                            Id = 4,
                            Nivel = "Book4",
                            PrecioLibro = 350m
                        },
                        new
                        {
                            Id = 5,
                            Nivel = "Book5",
                            PrecioLibro = 350m
                        },
                        new
                        {
                            Id = 6,
                            Nivel = "Book6",
                            PrecioLibro = 350m
                        });
                });

            modelBuilder.Entity("SistemaGabinos.Domain.Entities.Deuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Deudas");
                });

            modelBuilder.Entity("SistemaGabinos.Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId", "CursoId")
                        .IsUnique();

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("SistemaGabinos.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeudaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaCancelado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("SistemaGabinos.Domain.Entities.PrecioConfiguracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoExamenUbicacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoInscripcion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoLibro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoMensualidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoDescuentoBeca")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PreciosConfiguraciones");
                });

            modelBuilder.Entity("SistemaGabinos.Domain.Entities.Recibo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PagoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.ToTable("Recibos");
                });
#pragma warning restore 612, 618
        }
    }
}
